Repository thecyberworld/reconage, pull requests merged in 2022-10, with the labels that each got.

#2 Added new tool amass
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#3 included new finder called crt.sh
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#4 have added subfinder
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#6 find domain
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#7 added tools to resolve sub domains .
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#8 new feature to fetch url
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#9 have embeded url sortner
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#10 added new feature to find cnames.
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#11 have included more feature in cname
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete

#12 added new tool called subzy.
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#13 include feature to filter Javascript files.
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#14 include lfi scanner
  reconage.sh
Labels: ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#15 include SQLi scanner
  reconage.sh
Labels: ⭐ goal: addition, 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest

#16 include ssrf scanner
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#17 include redirect scanner
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#18 include SSTI scanner
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#19 included CVE automated scanner.
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#20 have include automated vulnerablity scanner
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#21 Include feature to scan misconfiguration
  reconage.sh
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, no-issue-activity, hacktoberfest

#22 include feature to filter invalid subdomain.
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#23 feat: dev subdomains finder
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#24 add ending message after script completed its task
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#25 add new tool nikto
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#27 add : New tool naabu for port enumeration
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#28 Update reconage.sh
  reconage.sh
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest

#29 add: New tool uncover added for ip enumeration
  reconage.sh
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest

#30 reconage.sh
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#32 add: Live ip address filter
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#33 Add: Tcpdump
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#34 add: Pair Nikto with Metasploit
  reconage.sh
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest
